### ISSUE TITLE
Cant seem to run this..

### ISSUE THREAD

**Issue by gateway** [dnuffer/large_neural_style#3]
gateway@gateway-media:~/work/large_neural_style$ python3 large_neural_style.py --style /home/gateway/work/styles/star.jpg --content /home/gateway/work/images/home.jpg --content-weight 90.6e11 --output /home/gateway/work/large_neural_style/
Traceback (most recent call last):
  File "large_neural_style.py", line 6, in <module>
    import stylize
  File "/home/gateway/work/large_neural_style/stylize.py", line 10, in <module>
    import tiling
  File "/home/gateway/work/large_neural_style/tiling.py", line 333
    print "Failed:", result
                  ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("Failed:", result)?

any thoughts? I didnt really seed any example command lines in the docs.. thank you!

**Comment by greycubesgav** [comment]
This seems to be an issue between running under Python 2 and Python 3.

Replace:
`print "Failed:", result`
With:
`print ("Failed:", result)`
